spring:
  application:
    name: api-gateway
  profiles:
   active: dev
  config:
   import: optional:configserver:http://localhost:8006/configServer
  sleuth:
    reactor:
      instrumentation-type: decorate-on-each
  

management:
  endpoints:
    web:
      exposure:
        include: "*"
        

logging:
 file:
  name: E:/CentralLogging/app.log

okta:
 oauth2:
  client-id: 0oaa8taojhCHSUXHH5d7
  client-secret: 0gztqnXByfRhNAopdq-JQnCW2nKv2NL9wuZ_DQag
  issuer: https://dev-56351932.okta.com/oauth2/default
  audience: api://default
  scopes: openid, profile, email, offline_access

          

            
      