spring:
  application:
    name: contact-service
  profiles:
    active: dev
  config: 
   import: optional:configserver:http://localhost:8006/configServer


  
management:
    endpoints:
     web:
      exposure:
       include: "*"
logging:
 file:
  name: E:/CentralLogging/app.log
  
okta:
  oauth2:
    issuer: https://dev-56351932.okta.com/oauth2/default
    audience: api://default
  
  

 
   
